export const SITE_CONFIG = {
  SITE_URL: "https://neurolawyer.example.com",
  SITE_NAME: "뉴로이어 집단소송",
  FIRM_NAME: "뉴로이어 법률사무소",
  LAWYER_NAME: "이도연 변호사",
  REPRESENTATIVE: "김수열",
  AD_RESPONSIBLE: "이도연",
  FIRM_REG_NO: "588-14-01388",
  FIRM_ADDRESS: "서울특별시 서초구 강남대로 525, 세영제이타워 11층",
  FIRM_PHONE: "070-8098-0421",
  FIRM_EMAIL: "dylee@newlawyer.co.kr",
  CPO_NAME: "이도연",
  CPO_EMAIL: "dylee@newlawyer.co.kr",
  ADMIN_PASSWORD: "neurolawyer2026",
  FILING_FEE: 11000,
  SUCCESS_FEE_1ST: "10%",
  SUCCESS_FEE_2ND: "15%",
  SUCCESS_FEE_3RD: "20%",
} as const;
