export const SITE_CONFIG = {
  SITE_NAME: "뉴로이어 집단소송",
  FIRM_NAME: "뉴로이어 법률사무소",
  LAWYER_NAME: "이도연 변호사",
  REPRESENTATIVE: "이도연",
  AD_RESPONSIBLE: "이도연",
  FIRM_REG_NO: "000-00-00000",
  FIRM_EMAIL: "",
  CPO_NAME: "이도연",
  CPO_EMAIL: "",
  ADMIN_PASSWORD: "neurolawyer2026",
  FILING_FEE: 11000,
  SUCCESS_FEE_1ST: "10%",
  SUCCESS_FEE_2ND: "15%",
  SUCCESS_FEE_3RD: "20%",
} as const;
